// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7tzxoCe1FOEgJe49-pDG1LW8RA3XWXWo',
    appId: '1:897429765386:web:084fcce442b50d4cd30ef3',
    messagingSenderId: '897429765386',
    projectId: 'bhatbhate-525d4',
    authDomain: 'bhatbhate-525d4.firebaseapp.com',
    storageBucket: 'bhatbhate-525d4.appspot.com',
    measurementId: 'G-799LSQTWFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF2TPVbiSdzBVJcBrXjE4F-WUvK9SfgSo',
    appId: '1:897429765386:android:04e65bd9b3f83950d30ef3',
    messagingSenderId: '897429765386',
    projectId: 'bhatbhate-525d4',
    storageBucket: 'bhatbhate-525d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSK5V3ur8AzW7_WabuTuTplyAQl-4lOBg',
    appId: '1:897429765386:ios:fdd928e967d6321fd30ef3',
    messagingSenderId: '897429765386',
    projectId: 'bhatbhate-525d4',
    storageBucket: 'bhatbhate-525d4.appspot.com',
    iosClientId: '897429765386-rebl75qucf1e89aj31ne3hq5knp0n93a.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhatbhate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSK5V3ur8AzW7_WabuTuTplyAQl-4lOBg',
    appId: '1:897429765386:ios:6411a8dbd8983b38d30ef3',
    messagingSenderId: '897429765386',
    projectId: 'bhatbhate-525d4',
    storageBucket: 'bhatbhate-525d4.appspot.com',
    iosClientId: '897429765386-v31h5g5aslsti46atnhluqane5oo30ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhatbhate.RunnerTests',
  );
}
